---
language: python

services:
  - docker

branches:
  only:
    - master

env:
  global:
    - YAMLLINT_VERSION=1.8.1
    - HADOOP_VERSION=2.7.7
    - HADOOP_OPENSTACK_VERSION=2.7.5
    - SPARK_VERSION=2.3.2
    - Z_VERSION=0.8.0
    - DOCKER_VERSION=18.06.1-ce
  matrix:
    - >
      TAG=latest-gpu
      TF_VERSION=1.10.1-gpu-py3
    - >
      TAG=latest
      TF_VERSION=1.10.1-py3
install:
  - docker pull lukasmartinelli/hadolint
  - docker pull boiyaa/yamllint:$YAMLLINT_VERSION

before_script:
  # Check code format
  - docker run --rm -i lukasmartinelli/hadolint hadolint --ignore DL3015 --ignore DL3008 - < Dockerfile
  - docker run -v "$PWD:/workdir" "boiyaa/yamllint:$YAMLLINT_VERSION" -c .yamllint.yml -s $(find . -name '*.yml')

script:
  - tag="mcapuccini/spark-tensorflow:$TAG"
  - >
    docker build
    --build-arg TF_VERSION=${TF_VERSION}
    --build-arg HADOOP_VERSION=${HADOOP_VERSION}
    --build-arg HADOOP_OPENSTACK_VERSION=${HADOOP_OPENSTACK_VERSION}
    --build-arg SPARK_VERSION=${SPARK_VERSION}
    --build-arg Z_VERSION=${Z_VERSION}
    --build-arg DOCKER_VERSION=${DOCKER_VERSION}
    --cache-from $tag
    --tag $tag
    .
after_success:
  - >
    if [ $TRAVIS_BRANCH = 'master' ] && [ $TRAVIS_PULL_REQUEST = 'false' ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      docker push $tag
    fi
